javax.net.ssl.trustStore=C:/Users/juans/Downloads/Wallet_DBOracle2/truststore.jks
javax.net.ssl.trustStorePassword=Cazafantasmas32
javax.net.ssl.keyStore=C:/Users/juans/Downloads/Wallet_DBOracle2/keystore.jks
javax.net.ssl.keyStorePassword=Cazafantasmas32
javax.net.ssl.trustStoreType=JKS
javax.net.ssl.keyStoreType=JKS