db=oracle
driver=oracle.jdbc.OracleDriver
conn=jdbc:oracle:thin:@dboracle_high?TNS_ADMIN=C:/Users/juans/Downloads/Wallet_DBOracle2
user=benchmarksql
password=Bmsql123456#
warehouses=1
loadWorkers=1
terminals=1
runTxnsPerTerminal=0
runMins=5
limitTxnsPerMin=10000000
terminalWarehouseFixed=false
useStoredProcedures=false